// Generated by BUCKLESCRIPT VERSION 4.0.1, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Future = require("reason-future/src/Future.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var KafkaNode = require("kafka-node");

function errorHandler(error) {
  console.log("error: ", error);
  return Pervasives.failwith("Fatal");
}

function make(client, readyHandler) {
  var producer = new KafkaNode.Producer(client);
  producer.on("error", errorHandler);
  producer.on("ready", (function () {
          return Curry._1(readyHandler, producer);
        }));
  return /* () */0;
}

function send(topic, producer, message) {
  return Future.make((function (resolve) {
                var messages = /* array */[message];
                producer.send(/* array */[{
                        topic: topic,
                        messages: messages
                      }], (function (err, res) {
                        if (err == null) {
                          console.log("message send success:", res);
                          return Curry._1(resolve, /* Ok */Block.__(0, [res]));
                        } else {
                          return errorHandler(String(err));
                        }
                      }));
                return /* () */0;
              }));
}

var K = 0;

exports.K = K;
exports.errorHandler = errorHandler;
exports.make = make;
exports.send = send;
/* kafka-node Not a pure module */
